### ISSUE TITLE
feat: Create a Python Typing Game

### ISSUE THREAD

**Issue by purnasth** [MrB141107/Python_Projects#71]
# Issue Title: Create a Python Typing Game

## Issue Description:
I propose the addition of a new project, a Python Typing Game, to the **Python_Projects** repository. Typing games are both fun and educational, helping users improve their typing speed and accuracy. 

## Project Details:
- **Name**: Python Typing Game
- **Technologies**: Python

## Additional Information (if available):
If there are specific guidelines or requirements for contributing to the repository, please provide the necessary details to ensure a smooth integration of this project.

I'm eager to work on this project and look forward to the opportunity to contribute to the repository. Thank you for considering this addition.

**Comment by RathodBhavya** [comment]
@purnasth, I am glad to know that you wanted to make your contribution towards this repository. Follow the directed steps to contribute towards this repository :

1. Fork this repo.
2. Add your files to appropriate directories.
3. Commit changes.
4. Create a pull request.

Hope to see your invaluable contribution soon...
